apiVersion: apps/v1
kind: Deployment
metadata:
  name: vite-react-demo
  labels:
    app: vite-react-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vite-react-demo
  template:
    metadata:
      labels:
        app: vite-react-demo
    spec:
      containers:
        - name: vite-react-demo
          imagePullPolicy: IfNotPresent
          image: registry.cn-hangzhou.aliyuncs.com/robin-registry/vite-react-demo:latest
          ports:
            - containerPort: 3000
#          resources:
#            requests:
#              memory: "256Mi"
#              cpu: "100m"
#            limits:
#              memory: "512Mi"
#              cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: vite-react-demo
spec:
  selector:
    app: vite-react-demo
  ports:
    - name: http-traffic
      port: 80
      protocol: TCP
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vite-react-demo
  labels:
    app: vite-react-demo
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - react.robin.lan  # 填写你的域名
      secretName: robin-lan-wildcard-tls # 存储证书的 Secret
  rules:
    - host: react.robin.lan
      http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: vite-react-demo
                port:
                  number: 80

